import Link from 'next/link'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service — ClearSign',
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      <nav className="border-b border-slate-200 px-6 py-4">
        <div className="max-w-3xl mx-auto">
          <Link href="/" className="text-slate-900 font-bold text-xl tracking-tight hover:opacity-80 transition-opacity">
            Clear<span className="text-blue-600">Sign</span>
          </Link>
        </div>
      </nav>

      <div className="max-w-3xl mx-auto px-6 py-16">
        <h1 className="text-3xl font-bold text-slate-900 mb-2">Terms of Service</h1>
        <p className="text-slate-400 text-sm mb-12">Last updated: March 2026</p>

        <div className="prose prose-slate max-w-none space-y-10">

          <section>
            <h2 className="text-lg font-bold text-slate-900 mb-3">What ClearSign does</h2>
            <p className="text-slate-600 leading-relaxed">
              ClearSign is an AI-powered contract analysis tool. We use artificial intelligence to read PDF documents and identify clauses that may carry risk, require attention, or benefit from legal review. ClearSign is a software tool, not a law firm. We do not provide legal advice, legal representation, or legal opinions. The output of ClearSign is informational only and does not constitute advice of any kind.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-slate-900 mb-3">What we do with your data</h2>
            <p className="text-slate-600 leading-relaxed">
              When you upload a PDF, the document text is extracted and sent to our AI provider for analysis. This text is used solely to generate your contract review. <strong className="text-slate-800">Document text is not stored after analysis is complete.</strong> We retain the analysis results (risk score, clause summaries) in our database so you can access your review via its unique link. We do not use your contract content for training, advertising, or any purpose other than generating your review.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-slate-900 mb-3">Payment terms</h2>
            <p className="text-slate-600 leading-relaxed mb-3">
              ClearSign offers two paid tiers: pay-per-review ($9 per review) and a monthly subscription ($29/month).
            </p>
            <ul className="list-disc list-inside space-y-2 text-slate-600">
              <li><strong className="text-slate-800">Per-review purchases are non-refundable.</strong> Once a review has been generated, the credit has been consumed.</li>
              <li><strong className="text-slate-800">Subscriptions can be cancelled at any time.</strong> Cancellation takes effect at the end of the current billing period. You will not be charged again after cancelling.</li>
              <li>A 7-day free trial is available for new monthly subscribers. Your card will not be charged until the trial ends.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold text-slate-900 mb-3">Disclaimer</h2>
            <p className="text-slate-600 leading-relaxed">
              ClearSign is not a law firm and does not provide legal advice. The analysis generated by ClearSign is for informational purposes only and should not be relied upon as a substitute for advice from a qualified attorney. Always consult a licensed attorney before signing any contract, especially for matters with significant financial or legal consequences. ClearSign makes no warranty, express or implied, as to the accuracy, completeness, or fitness for a particular purpose of any analysis generated.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-slate-900 mb-3">Governing law</h2>
            <p className="text-slate-600 leading-relaxed">
              These terms are governed by and construed in accordance with the laws of the State of Michigan, United States, without regard to conflict of law principles. Any disputes arising from your use of ClearSign shall be subject to the exclusive jurisdiction of the courts located in Michigan.
            </p>
          </section>

        </div>

        <div className="mt-16 pt-8 border-t border-slate-200 flex items-center gap-6 text-sm text-slate-400">
          <Link href="/" className="hover:text-slate-600 transition-colors">Home</Link>
          <Link href="/privacy" className="hover:text-slate-600 transition-colors">Privacy Policy</Link>
        </div>
      </div>
    </div>
  )
}
